on:
  push:

defaults:
  run:
    shell: bash

jobs:
  python-artifact:
    runs-on: ubuntu-latest
    name: "python artifact"

    env:
      CR_PAT: ${{ secrets.CR_PAT }}
      REPO_NAME: "kamynz/ci-cd-artifact-python"
      IMAGE_NAME: "artifact-python-demo:latest"

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Build
      run: |
        docker build -t artifact-python-demo:latest .
        docker tag artifact-python-demo:latest ghcr.io/${{ REPO_NAME }}/artifact-python-demo:latest

    - name: Deploy
      run: |
        echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
        docker push ghcr.io/${{ REPO_NAME }}/artifact-python-demo:latest

      #This can be use in other infrastructure to run.

